import Head from "next/head";
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillYoutube } from 'react-icons/ai';
import Image from "next/image";
import self_image from "../public/self_image.jpeg";
import djs_arya from "../public/djs_arya.png";
import react_logo from "../public/react-logo.png";
import nodejs_logo from "../public/Nodejs.jpeg";
import d3js_logo from "../public/d3js_logo.png"
import { useState } from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Harshil Suvarna Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-2 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="mx-5 py-10 mb-12 flex justify-between mr-2">
            <h1 className="text-xl dark:text-teal-500">Harshil Suvarna</h1>
            <ul className="flex items-center">
              <li className="cursor-pointer text-2xl px-2">
                <BsFillMoonStarsFill className="dark:text-white" onClick={() => setDarkMode(!darkMode)} />
              </li>
              <li>
                <a href="#" className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 font-mono font-bold">
            <h2 className="text-3xl text-teal-500">I'm Harshil Suvarna</h2>
            <h3 className="text-xl py-5 text-cyan-400">Developer and Analyst</h3>
            <p className="leading-7 text-gray-600 dark:text-gray-300">A passionate Data and ML Engineer with a Master’s in Information Systems from the UMD.</p>
            <p className="leading-7 text-gray-600 dark:text-gray-300">Let's connect and explore the power of data together</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-300">
            <AiFillLinkedin className="hover:shadow-lg hover:shadow-purple-500"/>
            <AiFillYoutube className="hover:shadow-lg hover:shadow-teal-500"/>
          </div>
          <div className="mt-20 flex justify-center">
            <div className="rounded-full overflow-hidden w-80 h-80 hover:shadow-2xl hover:shadow-purple-500">
              <Image src={self_image} className="object-cover hover:scale-110 hover:delay-200 transition-transform" />
            </div>
          </div>
        </section>

        {/* Services I offer section */}
        <section>
          <div>
            <h3 className="text-3xl text-center mt-5 py-10 text-gray-600 dark:text-gray-300">My Projects</h3>
          </div>
          <div className="mx-20 shadow-lg dark:shadow-lg dark:shadow-teal-500 hover:scale-110 hover:transition-transform">
            <div className="text-center shadow-lg p-10 rounded-xl  dark:shadow-lg dark:shadow-teal-500">
              <div className="flex justify-center">
                <Image src={djs_arya} width={100} height={100} />
              </div>
              <a href="https://www.cansatcompetition.com/" className="text-teal-400 hover:text-teal-500 "><h3 className="py-2">DJS ARYA - CanSat Competition</h3></a>
              <p className="text-gray-600 dark:text-white">
                The CanSat Competition is an annual event where students design, build, and launch a satellite the size of a soda can to meet specific mission objectives. The competition simulates the entire life cycle of a complex engineering and aeronautics project, from conceptual design to post-mission debrief.
              </p>
              <p className="text-gray-600 dark:text-white">Won 9th and 12th rank overall in the CanSat Competition held in Virginia, USA</p>
              <div className="text-center">
                <h4 className="py-4 text-teal-600 dark:text-teal-400">Tools Used</h4>
                <div className="flex-row">
                  <div className="flex justify-center py-2">
                    <Image src={react_logo} width={30} height={30} />
                    <p className="ml-5 text-gray-600 dark:text-gray-300">React.js</p>
                  </div>
                  <div className="flex justify-center">
                    <Image src={nodejs_logo} width={30} height={30} />
                    <p className="ml-5 text-gray-600 dark:text-gray-300">Node.js</p>
                  </div>
                  <div className="flex justify-center py-2">
                    <Image src={d3js_logo} width={30} height={30} />
                    <p className="ml-10 text-gray-600 dark:text-gray-300">D3.js</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
